question_generate: # 题目生成相关配置
  ollama_model_name: "deepseek-r1:7b"  # ollama模型名称
  use_api: true  # 是否使用API提供商
  api:
    api_key: "sk-175706aca2334a648482fe331b7e57c8" # 如果使用api，则需要提供api_key
    model_name: "qwen-max" # 模型名
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1" # 如果使用openai，则需要提供base_url


database: # 数据库配置
  host: "localhost" # 数据库主机
  port: 3306 # 数据库端口
  user: "root" # 数据库用户名
  password: "123456" # 数据库密码
  name: "popquiz" # 数据库名


upload_dir: "C:/popquiz_file"  # 上传文件的根目录
libreoffice_executable: "C:/Program Files/LibreOffice/program/soffice.exe"  # 用于PPT转PDF


flask_port: 5000 # flask监听端口

